// Core interfaces for the simplified 3-agent system

export interface GenerationInput {
  businessName: string
  industry: string
  description: string
  services: string[]
  contactEmail?: string
  contactPhone?: string
  contactAddress?: string
  heroImage?: string
  logoImage?: string
}

// Brand Context Agent Output
export interface BrandContext {
  personality: string[]
  tone: {
    primary: string
    modifiers: string[]
    description: string
  }
  targetAudience: string
  uniqueValueProps: string[]
  messagingFramework: {
    primaryMessage: string
    supportingMessages: string[]
    avoidanceList: string[]
  }
  competitorDifferentiators: string[]
  keywords: string[]
  industry: string
  confidence: number
  executionTime: number
}

// Content Generation Agent Output
export interface ContentGenerationOutput {
  hero: {
    title: string
    subtitle: string
    cta_text: string
  }
  about: {
    title: string
    description: string
  }
  services: {
    title: string
    items: Array<{
      name: string
      description: string
      price?: string | null
      icon?: string
    }>
  }
  contact: {
    title: string
    email?: string | null
    phone?: string | null
    address?: string | null
  }
  executionTime: number
}

// Quality Assurance Agent Output
export interface QualityAssuranceOutput extends ContentGenerationOutput {
  qualityScore: number
  enhancementsApplied: string[]
  validationReport: ValidationReport
}

// Type-safe agent results
export interface AgentResults {
  brandContext?: BrandContext
  creativeDirector?: import('../shared/design-tokens').CreativeDirectorOutput
  contentGeneration?: ContentGenerationOutput
  qualityAssurance?: QualityAssuranceOutput
}

// Shared context across all agents
export interface SharedContext {
  input: GenerationInput
  agentResults: AgentResults
  generationMetadata: {
    traceId: string
    startTime: number
    completedAgents: string[]
    totalExecutionTime?: number
  }
  validationRules: {
    requiredElements: string[]
    brandConsistencyThreshold: number
    qualityThreshold: number
  }
}

// Base agent interface
export interface Agent<TInput, TOutput> {
  name: string
  process(input: TInput, context: SharedContext): Promise<TOutput>
  validate(output: TOutput): boolean
  getRequiredInputs(): string[]
}

// Agent execution result
export interface AgentResult<T> {
  success: boolean
  data?: T
  error?: string
  executionTime: number
  fallbackUsed: boolean
}

// Validation interfaces
export interface ValidationIssue {
  type: 'brand_consistency' | 'content_quality' | 'technical' | 'grammar'
  severity: 'low' | 'medium' | 'high'
  description: string
  location: string
  suggestedFix?: string
}

export interface ValidationReport {
  score: number
  issues: ValidationIssue[]
  overallAssessment: string
}

export interface ConsistencyScore {
  score: number
  reasoning: string
  issues: string[]
}

// Final output type (matches existing PageContent)
export interface PageContent {
  hero: {
    title: string
    subtitle: string
    cta_text?: string
  }
  about: {
    title: string
    description: string
  }
  services: {
    title: string
    items: Array<{
      name: string
      description: string
      price?: string | null
      icon?: string
    }>
  }
  contact: {
    title: string
    email?: string | null
    phone?: string | null
    address?: string | null
    hours?: string
  }
  imageUrl?: string
  // Design system generated by Creative Director
  designTokens?: import('./design-tokens').DesignTokens
}

// Generation result with metadata
export interface GenerationResult {
  success: boolean
  data?: PageContent
  error?: string
  context: SharedContext
}